#!/bin/bash
set -euo pipefail
CARDS=`curl --no-progress-meter --fail-with-body https://api.scryfall.com/bulk-data/default_cards`
URI=$(grep -oP '"jsonl_download_uri":"\K[^"]*' <<< "$CARDS") || {
    echo "Error: grep could not find 'jsonl_download_uri' in the API response." >&2
    echo "Raw API Response: $CARDS" >&2
    exit 1
}
wget "$URI" --progress=dot:giga -O - | gunzip > scryfall-default-cards.jsonl
